# Generated by Django 4.2.19 on 2025-03-03 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_title', models.CharField(max_length=100)),
                ('lesson_description', models.CharField(max_length=1000)),
                ('lesson_image', models.ImageField(upload_to='lesson_images/')),
                ('lesson_video', models.FileField(upload_to='lesson_videos/')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_title', models.CharField(max_length=100)),
                ('module_description', models.CharField(max_length=1000)),
                ('module_image', models.ImageField(upload_to='module_images/')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_title', models.CharField(max_length=100)),
                ('slide_text', models.TextField(max_length=1000)),
                ('slide_image', models.ImageField(upload_to='slide_images/')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.module')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.JSONField()),
                ('correct_option', models.CharField(max_length=100)),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.slide')),
            ],
        ),
    ]
