# Generated by Django 4.2.19 on 2025-05-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_lesson_lesson_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='module',
            name='module_image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='slide_image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
